### ISSUE TITLE
dag.to.cpdag not considering layer.struct

### ISSUE THREAD

**Issue by tavazzie** [sambofra/bnstruct#22]
Hi!
First of all congrats for your package!
We've a question on the dag.to.cpdag function in [BN-methods.R](https://github.com/sambofra/bnstruct/blob/master/R/BN-methods.R).

We're learning a BN using the bootstrap procedure, giving as inputs both the parameter _layering_ and _layer.struct_. 
We've noticed that the resulting wpdag does not respect the rules among variables imposed through the layer.struct parameter.

By debugging the code, we found out that this issue appears when the dag.to.cpdag function is executed.
Indeed this function only requires the _dag_ and the _layering_ parameters, but does not consider the specified layer structure.
This results in:

label[ intersect(xedge,which(layering==l)), intersect(yedge,**which(layering>l)**) ] <- 
        dgraph[ intersect(xedge,which(layering==l)), intersect(yedge,**which(layering>l)**) ]

considering only the "default" allowed dependency among layers as described in the package documentation ("variables in
layer j can have parents only in layers i ≤ j"), but does not consider that some dependencies may have been overwritten in the layer structure.

We try to be more concrete with an example.
Let's suppose we've our variables {a,b,c,d,e,f} organized in these specified layers:
layer 1: a, b, c
layer 2: d, e
layer 3: f
by default, this layering would imply that **f** can have parents in layers 1, 2 and 3 (since they're above it or equal to it level).
Let's suppose that in the layer structure we deny that **f** can have layer 2 as a parent.
If in the dag the (allowed) edge **d**->**f** appears, the dag.to.cpdag function currently adds to the cpdag the **f**->**d** edge. This happens since dag.to.cpdag (see code string reported above) only looks at the layering, not at the _layer.struct_ parameter.
Shouldn't the _layer.struct_ be considered at well?

Thank you for your support and greetings from UNIPD ;)

**Comment by albertofranzin** [comment]
Ciao :)

yes, that seems to be a bug. I will try to fix it as soon as I can. Thank you for the debugging and the detailed report, it's really helpful!

Grazie a te, e saluti :)

**Comment by albertofranzin** [comment]
Ciao,

can you please check if the last commit solves the issue? I did some quick tests and it seems fine but it's always tricky to come up with test that are representative of all the possible cases.

Grazie ancora!

**Comment by tavazzie** [comment]
Hi! :)

We just checked the last version, and we confirm that it now works as expected.
Thank you so much!

We've seen that you've also updated the related documentation, please notice that the third argument is missing in the "Usage" field:
![dag to cpdag_documentation](https://user-images.githubusercontent.com/33624199/118676880-13fe3300-b7fc-11eb-8f39-540b8e98a090.PNG)

Thank you again :)

**Comment by albertofranzin** [comment]
Great, thanks for testing and for spotting that, I fixed the manual and I'll submit the package to the CRAN.

I'm closing the issue, of course in case you find any other problems feel free to reopen this one, or to open a new one.

Grazie, ciao :)
