### ISSUE TITLE
Compute score of a learnt network

### ISSUE THREAD

**Issue by indu-bodala** [sambofra/bnstruct#24]
Hi, 

Is there a way that I can calculate the BIC/BDeu score of the learnt network or read the output of the scoring function somewhere?

**Comment by albertofranzin** [comment]
Hello,

the scoring functions are not exposed. They are implemented in C, and are accessed directly using `.Call()`. See for example line 75 of https://github.com/sambofra/bnstruct/blob/master/R/mmhc.R.

**Comment by indu-bodala** [comment]
Thank you for the response. I will see if I can work around it.
