### ISSUE TITLE
Variable length sequence

### ISSUE THREAD

**Issue by ae-droid** [sambofra/bnstruct#27]
Hi, thank you for the package, it is brilliant. I have a question about learning the structures for the sequences with varying length. For example, assume that we are recording 4 outcomes for a group of students and student A has observations for 5 consecutive time steps, student B has 8 consecutive time steps etc.  How the package handles those cases for discovering  DBN? I am not sure if i am missing something you have already shared in the manual. If this is the case apologies, otherwise any comment of yours qould be extremely helpful. Thank you.

**Comment by albertofranzin** [comment]
Hi, and thank you.

The input dataset is essentially assumed to be a table, so the number of time steps considered is the same for all the observations, and it corresponds to the maximum value available. The missing time steps, e.g. time steps 6, 7 and 8 for student A, are considered missing values (NAs), and you have to indicate them as such.

Hope this helps.

**Comment by ae-droid** [comment]
Thank you very much for your respond, best.
