### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [sambofra/bnstruct#31]
@albertofranzin @sambofra @adw96: This package fails its checks for the release candidate for igraph 2.0.0. See <https://github.com/igraph/rigraph/blob/main/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph")` .

We're planning to release igraph 2.0.0 in mid-January. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by albertofranzin** [comment]
Hello, thanks for the heads up.

I updated the calls to the igraph functions
- graph.adjacency -> graph_from_adjacency_matrix
- get.adjacency -> as_adjacency_matrix

This should be all. The test files now run successfully.

I'll close the issue, but I'll wait a few days before pushing the package to the CRAN. Please reopen this if you encounter any further problems.

Alberto
